### ISSUE TITLE
greetingcard.py

### ISSUE THREAD

**Issue by ruidazeng** [hliuliu/kattis_problems#2]
I have a very similar Pythonic solution to greeting card (https://open.kattis.com/problems/greetingcard) by hardcoding the only possible situations where pairs of points are exactly 2018 units apart. However, my solution failed with a "TLE" message failing on the 5/11 test case and I just couldn't figure out why.

Is your solution able to successful pass all the test cases on Kattis?

```python
T = int(input())

lattice = []
for _ in range(T):
    x, y = map(int, input().split())
    lattice.append((x, y))

count = 0
for index in range(len(lattice)):
    cur_x = lattice[index][0] 
    cur_y = lattice[index][1]
    for jndex in range(index, len(lattice)):
        
        nex_x = lattice[jndex][0]
        nex_y = lattice[jndex][1]
        
        if ((cur_x + 2018 == nex_x and cur_y == nex_y) or
        (cur_x - 2018 == nex_x and cur_y == nex_y) or
        (cur_x == nex_x and cur_y + 2018 == nex_y) or
        (cur_x == nex_x and cur_y - 2018 == nex_y) or
        # more
        (cur_x + 1118 == nex_x and cur_y + 1680 == nex_y) or
        (cur_x + 1118 == nex_x and cur_y - 1680 == nex_y) or
        (cur_x - 1118 == nex_x and cur_y + 1680 == nex_y) or
        (cur_x - 1118 == nex_x and cur_y - 1680 == nex_y) or
        # more
        (cur_x + 1680 == nex_x and cur_y + 1118 == nex_y) or
        (cur_x + 1680 == nex_x and cur_y - 1118 == nex_y) or
        (cur_x - 1680 == nex_x and cur_y + 1118 == nex_y) or
        (cur_x - 1680 == nex_x and cur_y - 1118 == nex_y)):
            count += 1
print(count)
```

**Comment by hliuliu** [comment]
Hi,

You are physically checking every pair of points, which is a n^2 algorithm. For each current point, generate all possible points that are the required units of distance. ( only 8 possibilities) then check if any of them is a point u already visited before. To do this, u must store ur history points in a set rather than a list so that querying the history is expected to be constant time.
________________________________
